# Generated by Django 4.2 on 2023-04-20 08:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('Inbound', 'Inbound'), ('Outbound', 'Outbound'), ('Found', 'Found'), ('Corrected', 'Corrected'), ('Disposed Of', 'Disposed Of')])),
                ('stock_level_initial', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_altered', models.IntegerField()),
                ('stock_level_final', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
