# Generated by Django 4.2 on 2023-04-20 08:47

from django.db import migrations, models
import django.db.models.deletion
import merchant.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=merchant.models.merchant_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='MerchantPartnerRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_supplier', models.BooleanField()),
                ('is_customer', models.BooleanField()),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='merchant.merchant')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partner.partner')),
            ],
        ),
        migrations.AddField(
            model_name='merchant',
            name='partners',
            field=models.ManyToManyField(related_name='merchants', through='merchant.MerchantPartnerRelationship', to='partner.partner'),
        ),
    ]
