name: ERP-project
dependencies:
  - python=3.11.2
  - pip=23.0.1
  - psycopg2=2.9.3
  - pip:
      - django==4.2
      - djangorestframework==3.14.0
      - djangorestframework-simplejwt==5.2.2
      - django-cors-headers==3.14.0
      - django-import-export==3.2.0
      - drf-yasg==1.21.5
      - flake8==6.0.0
      - gunicorn==20.1.0
      - Pillow==9.5.0