# Generated by Django 4.2 on 2023-04-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='error_item_not_assigned_item_specifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='error_item_not_assigned_purchase_price_net_eur',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='error_item_not_assigned_sale_price_net_eur',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='stock_level_total_current',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='stock_level_total_purchase_value_current',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='stock_level_total_sale_value_current',
            field=models.FloatField(default=0),
        ),
    ]
