# Generated by Django 4.2 on 2023-04-20 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModelSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField(blank=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('brand_collection', models.CharField(blank=True, max_length=50, null=True)),
                ('description_short', models.CharField(blank=True, max_length=150, null=True)),
                ('description_long', models.CharField(blank=True, max_length=1000, null=True)),
                ('style', models.CharField(blank=True, max_length=50, null=True)),
                ('care_instructions', models.CharField(blank=True, max_length=150, null=True)),
                ('item_model_changes', models.CharField(max_length=150)),
                ('item_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_model_specifications', to='item_model.itemmodel')),
            ],
        ),
    ]
