# Generated by Django 4.2 on 2023-04-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_alter_item_item_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock_level_total_current',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='stock_level_total_purchase_value_current',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='stock_level_total_sale_value_current',
            field=models.FloatField(default=0),
        ),
    ]
