# Generated by Django 4.2 on 2023-04-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='value_total',
            field=models.FloatField(default=0),
        ),
    ]
